# Generated by Django 4.2.3 on 2023-08-29 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_usuarios_delete_ingreso_delete_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='Usuario',
            new_name='usuario',
        ),
    ]
