# Generated by Django 4.2.3 on 2023-08-29 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_rename_usuario_usuarios_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
