# Generated by Django 4.2.3 on 2023-08-29 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='clave',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
