# Generated by Django 4.2.3 on 2023-08-29 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_rename_clave_usuario_password_remove_usuario_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='username',
            field=models.EmailField(max_length=254),
        ),
    ]
